export const CARS = [
  {
    name: 'BMW',
    models: [
      { name: 'X3' },
      { name: 'X5' },
      { name: 'X6' },
      { name: 'X7' },
      { name: 'M2 Couple' },
      { name: '4 Series Gran Couple' },
    ],
  },
  {
    name: 'Citroen',
    models: [
      { name: 'C5 Aircross' },
      { name: 'DS3 Crossback' },
      { name: 'C3 Aircross' },
      { name: 'C4 Cactus' },
      { name: 'Berlongo Multispace' },
    ],
  },
  {
    name: 'Lexus',
    models: [
      { name: 'UX 250h' },
      { name: 'NX 300h' },
      { name: 'LC 500' },
      { name: 'RX 350/200t' },
      { name: 'IS 200t' },
      { name: 'LS 500h' },
      { name: 'UX 200' },
    ],
  },
  {
    name: 'Mazda',
    models: [
      { name: 'CX-5' },
      { name: 'Mazda3' },
      { name: 'Mazda6' },
      { name: 'CX-30' },
      { name: 'CX-9' },
      { name: 'CX-3' },
      { name: 'MX-5 Roadster' },
    ],
  },
  {
    name: 'Mercedes-Benz',
    models: [
      { name: 'G-Class' },
      { name: 'A-Class' },
      { name: 'S-Class' },
      { name: 'Maybach' },
      { name: 'C-Class' },
      { name: 'E-Class' },
      { name: 'GLE-Class SUV' },
    ],
  },
  {
    name: 'MINI',
    models: [
      { name: 'Cooper S 5d' },
      { name: 'Cooper S Countryman' },
      { name: 'Cooper 5d' },
      { name: 'Cooper S' },
      { name: 'John Cooper Works Countryman' },
      { name: 'Cooper S Clubman' },
      { name: 'Hatchback 3D' },
      { name: 'Clubman' },
    ],
  },
  {
    name: 'Mitsubishi',
    models: [
      { name: 'Pajero Sport' },
      { name: 'L200' },
      { name: 'Eclipse Cross' },
      { name: 'Outlander' },
      { name: 'ASX' },
      { name: 'L200' },
      { name: 'Outlander PHEV' },
    ],
  },
  {
    name: 'Opel',
    models: [
      { name: 'Crossland X' },
      { name: 'Grandland X' },
      { name: 'Corsa E' },
      { name: 'Astra J Sedan' },
      { name: 'Insignia Grand Sport' },
      { name: 'Combo Life' },
      { name: 'Zafira Life' },
      { name: 'ADAM' },
    ],
  },
  {
    name: 'Peugeot',
    models: [
      { name: '108' },
      { name: '508' },
      { name: '5008' },
      { name: '408' },
      { name: 'Rifter' },
      { name: '3008' },
      { name: '2008' },
      { name: '508' },
    ],
  },
  {
    name: 'Porsche',
    models: [
      { name: 'Taycan' },
      { name: 'Cayenne' },
      { name: 'Panamera Turbo' },
      { name: 'Macan' },
      { name: '911 Turbo' },
      { name: 'Panamera' },
    ],
  },
  {
    name: 'Renault',
    models: [
      { name: 'Duster' },
      { name: 'Arkana' },
      { name: 'Logan' },
      { name: 'Sandero' },
      { name: 'Koleos' },
      { name: 'Clio R.S.' },
      { name: 'Captur' },
    ],
  },
  {
    name: 'Rolls-Royce',
    models: [
      { name: 'Phantom' },
      { name: 'Ghost' },
      { name: 'Dawn' },
      { name: 'Cullianan' },
    ],
  },
  {
    name: 'SEAT',
    models: [
      { name: 'Tarraco' },
      { name: 'CUPRA Ateca' },
      { name: 'Arona' },
      { name: 'Leon Cupra' },
      { name: 'Ateca' },
      { name: 'Leon ST Cupra' },
      { name: 'Leon ST' },
      { name: 'Alhambra' },
    ],
  },
  {
    name: 'Skoda',
    models: [
      { name: 'Kodiaq' },
      { name: 'Octavia' },
      { name: 'Superb' },
      { name: 'Karoq' },
      { name: 'Fabia' },
      { name: 'Kamiq' },
      { name: 'Citigo' },
    ],
  },
  {
    name: 'Suzuki',
    models: [
      { name: 'Jimny' },
      { name: 'SX4' },
      { name: 'Vitara' },
      { name: 'Vitara S' },
      { name: 'Dzire' },
      { name: 'Grand Vitara' },
    ],
  },
  {
    name: 'Tesla',
    models: [
      { name: 'Model 3' },
      { name: 'Model S' },
      { name: 'Model X' },
    ],
  },
  {
    name: 'Toyota',
    models: [
      { name: 'Camry' },
      { name: 'RAV4' },
      { name: 'RAV4 Hybrid' },
      { name: 'Land Cruiser 200' },
      { name: 'Proace Verso' },
      { name: 'Land Cruiser Prado' },
      { name: 'Camry Hybrid' },
      { name: 'Corolla' },
    ],
  },
];
